#!/bin/bash

echo "Updating official Arch Linux packages..."
sudo pacman -Syu --noconfirm

echo "Updating AUR packages..."
yay -Syu --noconfirm

echo "Updating Snap packages..."
sudo snap refresh

echo "System update complete!"

